import { useCallback, useEffect, useMemo, useState } from "react";
import { askAssistant, createEscalation, decideEscalation, fetchEscalations, fetchMetrics, fetchSummary, fetchTasks, seedDemoData } from "./api";
import type { AssistantResponse, DailySummary, DashboardMetrics, Escalation, Task } from "./types";

type View = "overview" | "tasks" | "assistant" | "governance";
type ChatMessage = { role: "user" | "assistant"; text: string; response?: AssistantResponse };
const emptyMetrics: DashboardMetrics = { total_tasks: 0, overdue_tasks: 0, completed_tasks: 0, completion_rate: 0, high_priority_open_tasks: 0, blocked_tasks: 0 };
const emptySummary: DailySummary = { report_date: "", total_tasks: 0, open_tasks: 0, completed_tasks: 0, overdue_tasks: 0, blocked_tasks: 0, high_priority_tasks: 0, focus_tasks: [], narrative: "" };
const formatDate = (value: string) => new Intl.DateTimeFormat("en-IN", { day: "2-digit", month: "short" }).format(new Date(value));

function App() {
  const [view, setView] = useState<View>("overview");
  const [metrics, setMetrics] = useState(emptyMetrics);
  const [summary, setSummary] = useState(emptySummary);
  const [tasks, setTasks] = useState<Task[]>([]);
  const [escalations, setEscalations] = useState<Escalation[]>([]);
  const [selectedTask, setSelectedTask] = useState<Task | null>(null);
  const [status, setStatus] = useState("");
  const [priority, setPriority] = useState("");
  const [region, setRegion] = useState("");
  const [question, setQuestion] = useState("");
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const load = useCallback(async () => {
    try {
      setLoading(true); setError("");
      const [nextMetrics, nextSummary, nextTasks, nextEscalations] = await Promise.all([fetchMetrics(), fetchSummary(), fetchTasks({ status, priority, region }), fetchEscalations()]);
      setMetrics(nextMetrics); setSummary(nextSummary); setTasks(nextTasks); setEscalations(nextEscalations);
      setSelectedTask((current) => current && nextTasks.some((task) => task.task_id === current.task_id) ? current : null);
    } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Unable to load workspace data"); }
    finally { setLoading(false); }
  }, [priority, region, status]);
  useEffect(() => { void load(); }, [load]);
  const loadDemo = async () => { try { await seedDemoData(); await load(); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Could not load demo data"); } };
  const ask = async (text = question) => { if (!text.trim()) return; setQuestion(""); setMessages((current) => [...current, { role: "user", text }]); try { const response = await askAssistant(text); setMessages((current) => [...current, { role: "assistant", text: response.answer, response }]); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Assistant unavailable"); } };
  const riskQueue = useMemo(() => [...tasks].sort((a, b) => b.risk_score - a.risk_score).slice(0, 5), [tasks]);

  return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">V</span><div><strong>VoiceIQ</strong><small>LITE / OPS COPILOT</small></div></div><div className="workspace-label">WORKSPACE <span>LOCAL DEMO</span></div><nav>{(["overview", "tasks", "assistant", "governance"] as View[]).map((item) => <button key={item} className={view === item ? "active" : ""} onClick={() => setView(item)}><span className={`nav-icon ${item}`} />{item === "overview" ? "Overview" : item === "tasks" ? "All tasks" : item === "assistant" ? "AI assistant" : "Governance"}{item === "assistant" && <em>NEW</em>}{item === "governance" && escalations.length > 0 && <em className="alert-count">{escalations.length}</em>}</button>)}</nav><div className="sidebar-footer"><span className="status-dot" /> Synthetic demo data<br /><small>Human approval required</small></div></aside><main className="content"><header className="topbar"><div><p className="eyebrow">THURSDAY, 24 SEPTEMBER 2026 <span className="live-dot" /> LIVE WORKSPACE</p><h1>{view === "overview" ? "Operations cockpit" : view === "tasks" ? "Task workspace" : view === "assistant" ? "Operations assistant" : "Governance center"}</h1><p className="subtitle">{view === "overview" ? "A clear view of what needs attention today." : view === "tasks" ? "Inspect, filter, and understand every operational task." : view === "assistant" ? "Ask grounded questions about work and operating policy." : "Review recommendations before any escalation moves forward."}</p></div><div className="top-actions"><span className="connection"><span className="status-dot" /> API connected</span><button className="refresh" onClick={() => void load()}>↻ Refresh</button></div></header>{error && <div className="error-banner">{error}<button onClick={() => setError("")}>Dismiss</button></div>}{loading && <div className="loading-line"><span /> Syncing workspace data…</div>}{view === "overview" && <Overview metrics={metrics} summary={summary} tasks={riskQueue} selectedTask={selectedTask} setSelectedTask={setSelectedTask} onLoadDemo={loadDemo} />}{view === "tasks" && <Tasks tasks={tasks} selectedTask={selectedTask} setSelectedTask={setSelectedTask} status={status} setStatus={setStatus} priority={priority} setPriority={setPriority} region={region} setRegion={setRegion} />}{view === "assistant" && <Assistant messages={messages} question={question} setQuestion={setQuestion} onAsk={ask} />}{view === "governance" && <Governance escalations={escalations} onCreate={async (taskId) => { await createEscalation(taskId); await load(); }} onDecide={async (id, decision) => { await decideEscalation(id, decision); await load(); }} />}</main></div>;
}

function Overview({ metrics, summary, tasks, selectedTask, setSelectedTask, onLoadDemo }: { metrics: DashboardMetrics; summary: DailySummary; tasks: Task[]; selectedTask: Task | null; setSelectedTask: (task: Task) => void; onLoadDemo: () => void }) { return <><section className="metrics-grid"><Metric label="Total tasks" value={metrics.total_tasks} note="Across all teams" /><Metric label="Overdue" value={metrics.overdue_tasks} note="Need immediate review" tone="danger" /><Metric label="Completion rate" value={`${metrics.completion_rate}%`} note={`${metrics.completed_tasks} completed`} tone="success" /><Metric label="High priority open" value={metrics.high_priority_open_tasks} note={`${metrics.blocked_tasks} currently blocked`} tone="warning" /></section><section className="summary-banner"><div className="summary-icon">✦</div><div><p className="eyebrow">TODAY'S MANAGER BRIEF</p><strong>{summary.narrative || "No summary available yet."}</strong></div><button onClick={() => document.getElementById("risk-queue")?.scrollIntoView({ behavior: "smooth" })}>View focus list →</button></section><section className="workspace-grid" id="risk-queue"><div className="panel queue-panel"><PanelHeading eyebrow="PRIORITIZED WORK" title="Risk queue" count={`${tasks.length} focus tasks`} /><p className="panel-description">Tasks ranked by transparent baseline risk factors.</p>{tasks.length ? <div className="risk-list">{tasks.map((task) => <button className={`risk-item ${selectedTask?.task_id === task.task_id ? "selected" : ""}`} key={task.task_id} onClick={() => setSelectedTask(task)}><span className={`risk-score ${riskTone(task.risk_score)}`}>{Math.round(task.risk_score)}</span><span className="risk-copy"><strong>{task.title}</strong><small>{task.task_id} · {task.region} · due {formatDate(task.due_date)}</small></span><span className="arrow">→</span></button>)}</div> : <EmptyState onLoadDemo={onLoadDemo} />}</div><TaskDetail task={selectedTask} /></section></>; }

function Tasks({ tasks, selectedTask, setSelectedTask, status, setStatus, priority, setPriority, region, setRegion }: { tasks: Task[]; selectedTask: Task | null; setSelectedTask: (task: Task) => void; status: string; setStatus: (value: string) => void; priority: string; setPriority: (value: string) => void; region: string; setRegion: (value: string) => void }) { return <section className="panel tasks-panel"><PanelHeading eyebrow="WORK INVENTORY" title="All tasks" count={`${tasks.length} records`} /><div className="filters"><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">All statuses</option><option value="open">Open</option><option value="in_progress">In progress</option><option value="blocked">Blocked</option><option value="completed">Completed</option></select><select value={priority} onChange={(event) => setPriority(event.target.value)}><option value="">All priorities</option><option value="critical">Critical</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select><input value={region} onChange={(event) => setRegion(event.target.value)} placeholder="Filter region" /></div><div className="table-wrap"><table><thead><tr><th>Task</th><th>Region / team</th><th>Status</th><th>Due</th><th>Progress</th><th>Risk</th></tr></thead><tbody>{tasks.map((task) => <tr key={task.task_id} onClick={() => setSelectedTask(task)}><td><strong>{task.title}</strong><small>{task.task_id}</small></td><td>{task.region}<small>{task.team}</small></td><td><span className={`badge ${task.status}`}>{task.status.replace("_", " ")}</span></td><td className={task.is_overdue ? "overdue" : ""}>{formatDate(task.due_date)}</td><td><div className="mini-progress"><span style={{ width: `${task.progress_pct}%` }} /></div><small>{task.progress_pct}%</small></td><td><span className={`risk-text ${riskTone(task.risk_score)}`}>{Math.round(task.risk_score)}</span></td></tr>)}</tbody></table>{!tasks.length && <EmptyState />}</div>{selectedTask && <div className="inline-detail"><TaskDetail task={selectedTask} /></div>}</section>; }

function Assistant({ messages, question, setQuestion, onAsk }: { messages: ChatMessage[]; question: string; setQuestion: (value: string) => void; onAsk: (text?: string) => void }) { const suggestions = ["When should a task receive manager review?", "What fields are required in a task record?", "What should a daily summary include?"]; return <section className="assistant-layout"><div className="panel chat-panel"><PanelHeading eyebrow="GROUNDED OPERATIONS Q&A" title="Ask the assistant" count="SOP connected" /><div className="chat-history">{!messages.length && <div className="welcome-card"><span className="assistant-orb">✦</span><h3>Ask with confidence.</h3><p>Answers are retrieved from fictional operating policies and always show their sources.</p><div className="suggestions">{suggestions.map((suggestion) => <button key={suggestion} onClick={() => onAsk(suggestion)}>{suggestion} <span>→</span></button>)}</div></div>}{messages.map((message, index) => <div key={`${message.role}-${index}`} className={`message ${message.role}`}><span className="message-avatar">{message.role === "user" ? "You" : "V"}</span><div><p>{message.text}</p>{message.response?.citations.map((citation) => <small className="citation" key={citation.chunk_id}>⌁ {citation.source} · {citation.section}</small>)}</div></div>)}</div><form className="chat-form" onSubmit={(event) => { event.preventDefault(); onAsk(); }}><input value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Ask about tasks, policies, or blockers…" /><button aria-label="Send question">↑</button></form></div><div className="panel assistant-side"><p className="eyebrow">GROUNDING CONTROLS</p><h3>Evidence first</h3><p>VoiceIQ refuses to answer when the indexed SOPs do not support a question.</p><div className="control-row"><span className="check">✓</span><span>Source citations<br /><small>Every answer shows document evidence</small></span></div><div className="control-row"><span className="check">✓</span><span>Refusal behavior<br /><small>Unsupported claims are blocked</small></span></div></div></section>; }

function Governance({ escalations, onCreate, onDecide }: { escalations: Escalation[]; onCreate: (taskId: string) => Promise<void>; onDecide: (id: number, decision: "approved" | "rejected") => Promise<void> }) { return <section className="governance-grid"><div className="panel governance-intro"><p className="eyebrow">CONTROLLED ACTION</p><h2>Review before escalation</h2><p>Recommendations are deterministic, evidence-backed, and never sent automatically. Every decision is recorded in the audit trail.</p><div className="governance-stat"><strong>{escalations.length}</strong><span>pending recommendations</span></div></div><div className="panel escalation-panel"><PanelHeading eyebrow="RECOMMENDATIONS" title="Needs human review" count={`${escalations.length} pending`} />{escalations.length ? <div className="escalation-list">{escalations.map((escalation) => <div className="escalation-card" key={escalation.task_id}><div className="escalation-top"><span className="risk-score high">!</span><div><strong>{escalation.task_id}</strong><small>{escalation.rule_code}</small></div><span className="badge pending">Pending</span></div><p>{escalation.reason}</p><div className="evidence-tags">{(escalation.evidence.triggers as string[] | undefined)?.map((trigger) => <span key={trigger}>{trigger}</span>)}</div>{escalation.escalation_id ? <div className="decision-actions"><button className="approve" onClick={() => void onDecide(escalation.escalation_id!, "approved")}>Approve</button><button className="reject" onClick={() => void onDecide(escalation.escalation_id!, "rejected")}>Reject</button></div> : <button className="review-button" onClick={() => void onCreate(escalation.task_id)}>Create review record →</button>}</div>)}</div> : <EmptyState message="No pending recommendations." />}</div></section>; }

function TaskDetail({ task }: { task: Task | null }) { return <div className="panel detail-panel"><PanelHeading eyebrow="TASK DETAIL" title={task ? task.task_id : "Select a task"} count={task ? task.status.replace("_", " ") : "Awaiting selection"} />{task ? <div className="detail-content"><h3>{task.title}</h3><p className="detail-meta">{task.team} · {task.assignee} · {task.region}</p><div className="detail-risk"><span>Baseline risk score</span><strong className={riskTone(task.risk_score)}>{Math.round(task.risk_score)}<small>/100</small></strong></div><div className="progress-label"><span>Progress</span><span>{task.progress_pct}%</span></div><div className="progress"><span style={{ width: `${task.progress_pct}%` }} /></div><div className="evidence"><p className="eyebrow">WHY IT IS RISKY</p><p>{task.is_overdue ? "Past due date" : "Due date approaching"}; {task.previous_delay_count} previous delay{task.previous_delay_count === 1 ? "" : "s"}; {task.blocker ? `blocker: ${task.blocker}` : "no blocker recorded"}.</p></div></div> : <EmptyState message="Choose a task from the queue to inspect evidence." />}</div>; }
function PanelHeading({ eyebrow, title, count }: { eyebrow: string; title: string; count?: string }) { return <div className="panel-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div>{count && <span className="count-pill">{count}</span>}</div>; }
function Metric({ label, value, note, tone = "" }: { label: string; value: number | string; note: string; tone?: string }) { return <div className="metric-card"><span className="metric-label">{label}</span><strong className={tone}>{value}</strong><small>{note}</small></div>; }
function EmptyState({ message = "No task data loaded yet.", onLoadDemo }: { message?: string; onLoadDemo?: () => void }) { return <div className="empty-state"><span>◌</span><p>{message}</p>{onLoadDemo ? <button onClick={onLoadDemo}>Load 80 synthetic tasks →</button> : <small>Try refreshing or changing your filters.</small>}</div>; }
function riskTone(score: number) { return score >= 70 ? "high" : score >= 40 ? "medium" : "low"; }
export default App;
